services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: distriandina-simulator
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: unless-stopped
